version: "3.2"

services:
  oragono:
    image: oragono/oragono
    ports:
      - "6667:6667/tcp"
      - "6697:6697/tcp"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  traefik:
    external: true
